-- general --
require('options')
require('keymaps')
require('misc')

-- plugins --
require('plugins')
require('plug-config.lsp.init')
require('plug-config.autopairs')
require('plug-config.cmp')
require('plug-config.emmet')
require('plug-config.formatter')
require('plug-config.gitsigns')
require('plug-config.indent-blankline')
require('plug-config.lualine')
require('plug-config.nvim-tree')
require('plug-config.startup')
require('plug-config.telescope')
require('plug-config.toggleterm')
require('plug-config.treesitter')
